In [27]:
import pandas as pd 
df=pd.read_csv("labeled_data.csv")
df.head(3)

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet
0,0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24783 entries, 0 to 24782
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          24783 non-null  int64
 1   count               24783 non-null  int64
 2   hate_speech         24783 non-null  int64
 3   offensive_language  24783 non-null  int64
 4   neither             24783 non-null  int64
 5   class               24783 non-null  int64
 6   tweet               24783 non-null  object
dtypes: int64(6), object(1)
memory usage: 1.3+ MB

In [29]:
df.columns

Index(['Unnamed: 0', 'count', 'hate_speech', 'offensive_language', 'neither',
       'class', 'tweet'],
      dtype='object')

In [30]:
df.isnull().sum() #checking the number of missing values in each column

Unnamed: 0            0
count                 0
hate_speech           0
offensive_language    0
neither               0
class                 0
tweet                 0
dtype: int64

In [31]:
tweets=df.tweet #storing the tweet column of dataset into variable named tweets

In [32]:
df['class'].unique()

array([2, 1, 0], dtype=int64)

In [33]:
#DATA PREPROCESSING
#It aims to ensure that the data is clean, consistent, and suitable for training a machine learning model.

#1. Text Cleaning(removing punctuation,special charactersetc.)
#2. Tokenization (Breaking the text into individual words or tokens)
#3. Convert all text to lowercase
#4. Removing Stopwords(words that do not carry much meaning, such as "and," "the," "is," etc.)
#5. Stemming (Reduceing words to their base or root form)
# Handling Missing Data

In [34]:
import re
import nltk 
stemmer=nltk.SnowballStemmer("english")
from nltk.corpus import stopwords

In [35]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\nupur\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [36]:
import string  
stopword=set(stopwords.words("english"))

In [37]:
df['labels']= df['class'].map({0:"Hate Speech Detected",1:"Offevsive language Detected",2:"none"})
df.head(3)

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet,labels
0,0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...,none
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...,Offevsive language Detected
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...,Offevsive language Detected

In [38]:
df1=df[['tweet','labels']]
df1.head(3)

,tweet,labels
0,!!! RT @mayasolovely: As a woman you shouldn't...,none
1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...,Offevsive language Detected
2,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...,Offevsive language Detected

In [39]:
#The clean function here is designed to clean and transform a given text
def clean(twt):
    twt=str(twt).lower()
    twt=re.sub(r'\[.*?\]','',twt) # match the shortest sequence of characters between square brackets in a given text.
    twt = re.sub(r"https?://[^\s]+\.[^\s]+", "", twt)  # Removes any URL
    twt=re.sub(r'[^\w\s]','',twt) #to delete punctuations
    twt=re.sub(r'\n','',twt) #removes newline
    twt=re.sub(r'\w*\d\w*','',twt) #removes words with digits
    twt=[word for word in twt.split(' ')if word not in stopword] #removes stopwords
    twt=" ".join(twt) #join cleaned words back to string
    twt=[stemmer.stem(word) for word in twt.split(' ') ]#apply stemming to each word
    twt=" ".join(twt) #join stemmed words back to string
    return twt

In [40]:
df1["tweet"]=df1["tweet"].apply(clean) #apply clean function to tweet column

C:\Users\nupur\AppData\Local\Temp\ipykernel_34768\2418884873.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["tweet"]=df1["tweet"].apply(clean) #apply clean function to tweet column

In [41]:
import numpy as np #for numerical operations
from sklearn.feature_extraction.text import CountVectorizer  #for text feature extraction  will be used to convert the text data into a matrix of token counts.
from sklearn.model_selection import train_test_split  #for splitting data sets
from sklearn.tree import DecisionTreeClassifier  # for implementing decision tree-based classification

In [42]:
x=np.array(df1["tweet"])
y=np.array(df1["labels"])

cv = CountVectorizer()  # creates an instance of the CountVectorizer class 
x= cv.fit_transform(x)  #converts the text data into a sparse matrix of token counts
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.33,random_state=42)

In [43]:
model=DecisionTreeClassifier()
model.fit(X_train, y_train) #to train the decision tree classifier
y_predict=model.predict(X_test)

In [44]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_predict))

0.8689326323511432

In [49]:
data="lets kill jews and kill them for fun "
data=cv.transform([data]).toarray() #converts the sparse matrix representation of the transformed data into a dense NumPy array.( represents the token counts of the words in the input text, using the same vocabulary learned during training.)
print(model.predict((data))) #make predictions on the transformed data using the trained decision tree classifier

['Hate Speech Detected']

In [46]:

data="this bitch is getting on my nerves"
data=cv.transform([data]).toarray() 
print(model.predict((data)))

['Offevsive language Detected']

In [53]:
data="this b*tch is getting on my nerves"
data=cv.transform([data]).toarray()
print(model.predict((data)))

['none']

In [48]:
from sklearn.metrics import precision_score, classification_report

precision = precision_score(y_test, y_predict, average=None)
for i, label in enumerate(df['labels'].unique()):
    print(f'Precision for class "{label}": {precision[i]}')
print('\nClassification Report:\n', classification_report(y_test, y_predict, target_names=df['labels'].unique()))

Precision for class "none": 0.36363636363636365
Precision for class "Offevsive language Detected": 0.9141524105754277
Precision for class "Hate Speech Detected": 0.8091660405709993

Classification Report:
                              precision    recall  f1-score   support

                       none       0.36      0.33      0.34       465
Offevsive language Detected       0.91      0.93      0.92      6335
       Hate Speech Detected       0.81      0.78      0.79      1379

                   accuracy                           0.87      8179
                  macro avg       0.70      0.68      0.69      8179
               weighted avg       0.87      0.87      0.87      8179